POST http://localhost:8888/signup
Content-Type: application/json

{
  "name": "W_K.O 2",
  "email": "klodivilf@gmail.com",
  "password": "wK01234_"
}

###

POST http://localhost:8888/signin
Content-Type: application/json

{
  "email": "oficialwko@gmail.com",
  "password": "wK01234_"
}


###

POST http://localhost:8888/recovery
Content-Type: application/json

{
  "email": "klodivilf@gmail.com"
}


### 

POST http://localhost:8888/recovery/c22b456f-d692-4c6a-b199-34aeca5a7ff3
Content-Type: application/json

{
  "newPassword": "#K_12934eOW"
}

###

POST http://localhost:8888/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="testfile.txt"
Content-Type: text/plain

This is a test file.
------WebKitFormBoundary7MA4YWxkTrZu0gW--